### PR TITLE
Adding `stb_write_image` library

### PR DESCRIPTION
**Pull request by Wmbat**
Adding the `stb_write_image.h` header library to the `stb` project

### CODE REVIEW

**Comment by lyrahgames** [comment]
Hello,
thank you very much for your additional work.
May I suggest to remove the `.gitignore` files in your package directory?
They are unnecessary due to the used white-listing in the root directory.
Apart from that, I see no problems in merging the commit.

**Comment by Wmbat** [comment]
Hello,

I've removed the extra `.gitignore` files in the package directory.
I was also wondering whether it would be worth it just package a lot of the different stb libraries right away for completions' sake, what are your thoughts on that ? I wouldn't mind putting the work to add more of them

**Comment by lyrahgames** [comment]
> I've removed the extra `.gitignore` files in the package directory.

There seem to be more `.gitignore` files in the `stb_image_writer/build`, the `stb_image_writer/tests`, and the `stb_image_writer/tests/build` folders.

> I was also wondering whether it would be worth it just package a lot of the different stb libraries right away for completions' sake, what are your thoughts on that ? I wouldn't mind putting the work to add more of them

That sounds great.
Personally, until now, I have only used the `stb_image` library and I did not have the additional time to package and test the other libraries.
But if you are familiar with those and you want to spare some time and put the effort in it, I would be delighted.
I assume that it would then be better to make you contributor?

**Comment by Wmbat** [comment]
I think I've removed all the unnecessary `.gitignore` files.

I think PRs for each stb library I package is the best way to do it, as there would be some review process to make sure the packages are all uniform & properly done.

what do you think?

**Comment by lyrahgames** [comment]
> I think I've removed all the unnecessary `.gitignore` files.

Looks good to me.

> I think PRs for each stb library I package is the best way to do it, as there would be some review process to make sure the packages are all uniform & properly done.
> 
> what do you think?

If this does not mean too much overhead for you, then I am completely fine with accepting your pull requests.
I will then make sure to publish all the packages to cppget.org.

**Comment by boris-kolpackov** [comment]
Thanks for working on this!

**Pull request merged**
