### PR TITLE
Adding stb_truetype

### PR DESCRIPTION
**Pull request by duarm**
adding stb_truetype, I'll need some of the other stb libs for my project, so I might package all of them soon.

### CODE REVIEW

**Comment by lyrahgames** [comment]
Thank you very much for your work on this package and also for reminding me of it! I haven't properly updated this repository for some time, now. After reviewing your changes and taking a look into the repository itself, I realize that it needs a much bigger overhaul than only adding all other header libraries. I hope you don't mind but I can add all other libraries and refactor this repository in one go in the upcoming week and would reject your pull request, for now.

Apart from that, you might be interested in some comments concerning the content of your pull request:
- The version in the `manifest` file is not correct. I think it should be `1.26.0`.
- You have included the API documentation file from `stb_image` in the package, but this file doesn't belong to the `stb_truetype` package.
- In the `root.build`, you have marked the header file to be importable. As the stb libraries use external macros to be configurable, this is most likely not true. But I see that the packages for `stb_image_write` and `stb_image_resize` do the same mistake.

**Comment by duarm** [comment]
>   I hope you don't mind but I can add all other libraries and refactor this repository in one go in the upcoming week and would reject your pull request, for now.

that would help a lot

I missed the docs and I thought the version was universal for all stb packages (since they all share the repo). I'll close this then, thanks for taking the time to look it up

**Comment by boris-kolpackov** [comment]
@duarm FYI, the packages are now published:  https://cppget.org/?packages=stb

@lyrahgames Thanks, nice work!

**Comment by lyrahgames** [comment]
> @lyrahgames Thanks, nice work!

You are very welcome. Happy to do it ^^

**Pull request closed without merging**
